package proxy

import (
	"net/http"
	"net/http/httputil"
	"net/url"
)

var protectedHeaders = []string{
	"X-FPBridge-Event-ID",
	"X-FPBridge-JA3",
	"X-FPBridge-JA4",
	"X-FPBridge-HTTP2-Fingerprint",
	"X-FPBridge-Observed-IP",
	"X-FPBridge-Timestamp",
	"X-FPBridge-Signature",
	"Forwarded",
	"X-Forwarded-For",
	"X-Forwarded-Host",
	"X-Forwarded-Proto",
}

func removeProtectedHeaders(header http.Header) {
	for _, name := range protectedHeaders {
		header.Del((name))
	}
}

func New(upstream *url.URL) http.Handler {
	// Creates a pointer to a httputil.ReverseProxy
	reverseProxy := &httputil.ReverseProxy{
		// This function is called before forwarding every request
		Rewrite: func(request *httputil.ProxyRequest) {
			request.SetURL(upstream) // Changes outgoing request destination
			// Browser should not provide fields that are suppose to be generated by FP Bridge
			removeProtectedHeaders(request.Out.Header) // Remove headers that the public client must not control
			request.SetXForwarded()                    // Generate new headers after deleted untrusted forwarding headers
		},
	}
	// Return the pointer
	return reverseProxy
}
